name: Build Android APK

on:
  push:
    branches: [main, feature/*]
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_android:
    name: Build and Upload APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant Gradle Permissions
        working-directory: ./Fruitties
        run: chmod +x gradlew

      - name: Build Release APK
        working-directory: ./Fruitties
        run: ./gradlew assembleRelease --stacktrace || (echo "Build failed" && exit 1)

      - name: Debug Project Structure
        working-directory: ./Fruitties
        run: |
          echo "Current Directory: $(pwd)"
          ls -R

      - name: Find APK File
        working-directory: ./Fruitties
        run: |
          echo "Searching for APK files..."
          find . -name "*.apk"

      - name: Check APK Exists
        working-directory: ./Fruitties
        run: |
          if [ ! -f "app/build/outputs/apk/release/app-release.apk" ]; then
            echo "No APK found in the expected path."
          fi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fruitties-Release.apk
          path: Fruitties/app/build/outputs/apk/release/app-release.apk
