name: Build and Release APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant Permissions to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build Release APK
        working-directory: ./Fruitties/androidApp
        run: ./gradlew assembleRelease

      - name: Debug Project Structure
        working-directory: ./Fruitties/androidApp
        run: |
          echo "Current Directory: $(pwd)"
          ls -R ./build/outputs/apk/release/

      - name: Find and Check APK File
        id: find_apk
        working-directory: ./Fruitties/androidApp
        run: |
          echo "Searching for APK files..."
          APK_PATH=$(find ./build/outputs/apk/release/ -name "*.apk" | grep "release")
          if [ -z "$APK_PATH" ]; then
            echo "No APK found in the expected path."
            echo "APK_PATH=" >> $GITHUB_ENV
          else
            APK_PATH=$(realpath "$APK_PATH")  # Convert to absolute path
            echo "APK found at: $APK_PATH"
            echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          fi

      - name: Upload APK Artifact
        if: env.APK_PATH != ''
        uses: actions/upload-artifact@v4
        with:
          name: Fruitties-Release.apk
          path: ${{ env.APK_PATH }}
