name: Build Android APK

on:
  push:
    branches: [main, feature/*]
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_android:
    name: Build and Upload APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant Gradle Permissions
        working-directory: ./Fruitties
        run: chmod +x gradlew

      - name: Build Release APK
        working-directory: ./Fruitties
        run: ./gradlew assembleRelease --stacktrace

      - name: Find APK File
        working-directory: ./Fruitties
        run: |
          echo "APK Path: $(pwd)/app/build/outputs/apk/release/"
          ls -la app/build/outputs/apk/release/

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fruitties-Release.apk
          path: Fruitties/app/build/outputs/apk/release/*.apk
