name: Build Fruitties Sample

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant Gradle Permissions
        working-directory: ./Fruitties
        run: chmod +x gradlew

      - name: Build Release APK
        working-directory: ./Fruitties
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Fruitties-Release.apk
          path: Fruitties/app/build/outputs/apk/release/*.apk

  build_ios:
    name: Build iOS App
    runs-on: macos-latest
    steps:
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build iOS Project
        working-directory: ./Fruitties
        run: xcodebuild -project iosApp/iosApp.xcodeproj -configuration Debug -scheme iosApp -sdk iphonesimulator
